name: Sync Codetree Subtree

on:
  schedule:
    - cron: '0 16 * * *'  # 매일 KST 1시
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout algorithm repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure codetree remote
        run: |
          git remote remove codetree || true
          git remote add codetree https://github.com/sunkiteo-o/codetree.git
          git remote -v
          git fetch codetree

      - name: Pull codetree subtree
        run: |
          git subtree pull --prefix=codetree codetree main -m "chore(subtree): sync codetree"

      - name: Push updated subtree
        run: |
          git push origin main
